package com.solution.p2p.core.user.dao;

import java.util.List;

import com.solution.p2p.core.common.entity.SysUserIdentification;
import com.solution.p2p.core.common.entity.SysUserIdentificationExample;
import org.apache.ibatis.annotations.Param;

public interface SysUserIdentificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    int countByExample(SysUserIdentificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    int deleteByExample(SysUserIdentificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    int insert(SysUserIdentification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    int insertSelective(SysUserIdentification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    List<SysUserIdentification> selectByExample(SysUserIdentificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    SysUserIdentification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    int updateByExampleSelective(@Param("record") SysUserIdentification record, @Param("example") SysUserIdentificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    int updateByExample(@Param("record") SysUserIdentification record, @Param("example") SysUserIdentificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    int updateByPrimaryKeySelective(SysUserIdentification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_identification
     *
     * @mbggenerated Wed Oct 15 15:50:26 CST 2014
     */
    int updateByPrimaryKey(SysUserIdentification record);
}